language: java
sudo: false
install: true
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "booooza-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar