@startuml

title swe2-uno - Activity Diagram

partition Initialization {
  start
  :Player Registration;
  :Start Game;
  :Generate Deck;
  :Shuffle Deck;
  :Distribute Cards;
  :Reveal Top Card;
  :Choose Starting Player;
}

partition TurnLoop {
  while (Is there a winner?) is (false)
    if (Has matching card?) then (yes)
      :Mark matching cards;
      :Wait for user selection;
      :Play card;
    else (no)
      :Draw card;
      if (Is matching card?) then (yes)
        :Notify user;
        :Wait for user input;
        :Play card;
      else (no)
      endif
    endif
      if (Cards left in hand) then (1)
        :Uno;
      else if (0)
        :Winner;
      else if (>1)
      endif
    :Turn ends;
  endwhile (true)

partition End {
  :Announce winner;
  stop
}

@enduml
